export default {
  __init__: [
    'appendBehavior',
    'copyPasteBehavior',
    'createBoundaryEventBehavior',
    'createDataObjectBehavior',
    'dropOnFlowBehavior',
    'createParticipantBehavior',
    'dataInputAssociationBehavior',
    'deleteLaneBehavior',
    'importDockingFix',
    'labelBehavior',
    'modelingFeedback',
    'removeParticipantBehavior',
    'replaceConnectionBehavior',
    'replaceElementBehaviour',
    'resizeLaneBehavior',
    'unsetDefaultFlowBehavior',
    'updateFlowNodeRefsBehavior',
    'removeElementBehavior',
    'unclaimIdBehavior',
    'toggleElementCollapseBehaviour'
  ],
  appendBehavior: [ 'type', require('./AppendBehavior').default ],
  copyPasteBehavior: [ 'type', require('./CopyPasteBehavior').default ],
  createBoundaryEventBehavior: [ 'type', require('./CreateBoundaryEventBehavior').default ],
  createDataObjectBehavior: [ 'type', require('./CreateDataObjectBehavior').default ],
  dropOnFlowBehavior: [ 'type', require('./DropOnFlowBehavior').default ],
  createParticipantBehavior: [ 'type', require('./CreateParticipantBehavior').default ],
  dataInputAssociationBehavior: [ 'type', require('./DataInputAssociationBehavior').default ],
  deleteLaneBehavior: [ 'type', require('./DeleteLaneBehavior').default ],
  importDockingFix: [ 'type', require('./ImportDockingFix').default ],
  labelBehavior: [ 'type', require('./LabelBehavior').default ],
  modelingFeedback: [ 'type', require('./ModelingFeedback').default ],
  removeParticipantBehavior: [ 'type', require('./RemoveParticipantBehavior').default ],
  replaceConnectionBehavior: [ 'type', require('./ReplaceConnectionBehavior').default ],
  replaceElementBehaviour: [ 'type', require('./ReplaceElementBehaviour').default ],
  resizeLaneBehavior: [ 'type', require('./ResizeLaneBehavior').default ],
  unsetDefaultFlowBehavior: [ 'type', require('./UnsetDefaultFlowBehavior').default ],
  updateFlowNodeRefsBehavior: [ 'type', require('./UpdateFlowNodeRefsBehavior').default ],
  removeElementBehavior: [ 'type', require('./RemoveElementBehavior').default ],
  unclaimIdBehavior: [ 'type', require('./UnclaimIdBehavior').default ],
  toggleElementCollapseBehaviour : [ 'type', require('./ToggleElementCollapseBehaviour').default ]
};
